### ISSUE TITLE
Module 2 Capstone: Kanban project setup - 3 team members

### ISSUE THREAD

**Issue by Estete9** [Estete9/CapstoneShowFinder#21]
https://github.com/Estete9/CapstoneShowFinder/projects/1

note: 3 person team

**Comment by ademibowale** [comment]
Hi @Team, 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
 
- Cards should be assigned to team members in a fair way ✔️ 
- All cards with `group task` in the title should be assigned to someone ✔️ 
- Students' board should be a copy of [this template board](https://github.com/microverseinc/curriculum-javascript/projects/1)Students' board should be a copy of [this template board](https://github.com/microverseinc/curriculum-javascript/projects/1) ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
